### PR TITLE
Add DocMaps Sample with VoR for 86628

### PR DESCRIPTION
**Pull request by HazalCiplak**
https://github.com/elifesciences/data-hub-issues/issues/677
https://github.com/elifesciences/data-hub-issues/issues/719

### CODE REVIEW

**Comment by HazalCiplak** [comment]
Hi @scottaubrey, @nlisgo, @fred-atherden, @gnott, @de-code 

Could you please check out this DocMap sample for a manuscript with VoR and give me your thoughts? I'd appreciate your feedback to help me with the development process. 

Thanks!

**Comment by HazalCiplak** [comment]
Please note that in the "published" field, I have used the timestamp ("2023-05-15T17:19:12+00:00") from eJP for the decision "Pass to Production." On [the website](https://elifesciences.org/articles/86628), it appears as **June 2, 2023**. Therefore, it might be appropriate to use that date. 
So, we can consider including VoR publish date in our planned manual publish date import process if it seems feasible and there are no alternative methods for importing this data.

**Comment by gnott** [comment]
I like the new data step and the terms `"version-of-record"` and `"vor-published"`. It doesn't affect what I'm doing though, it causes no issues with my code.

I don't think there's a need at this point to also include the VOR peer reviews with the DOI values in the step too? I won't need these, but maybe they'll be important later for generating reports and metrics?

**Comment by HazalCiplak** [comment]
> I don't think there's a need at this point to also include the VOR peer reviews with the DOI values in the step too? I won't need these, but maybe they'll be important later for generating reports and metrics?

That's a great idea! Once we begin supporting VoRs in our DocMaps API, we can include the VOR peer reviews. To obtain the VOR peer reviews data, we should confirm whether it will be available in Hypothesis or any other platform. (I assume current example manuscript doesn’t have VOR peer review yet)

**Comment by scottaubrey** [comment]
This looks great to me, thanks @HazalCiplak !

RE: peer reviews for VoR, I think they are included as part of the VoR at publish time. I can see this article we're building around ([86628](https://elifesciences.org/articles/86628)) has dois for the peer review material (https://doi.org/10.7554/eLife.86628.3.sa0, https://doi.org/10.7554/eLife.86628.3.sa1, https://doi.org/10.7554/eLife.86628.3.sa2), and the material itself seems to be identical content to the revised preprint before it. 

To answer your question more directly @HazalCiplak, I'd guess the peer review content isn't posted anywhere else publicly besides as part of our VoR article (no hypothesis, no sciety as it's not peer review on a preprint) and it is published at the same time as the VoR. Further - I'm guessing the peer review material will be similar, or the same as the previous reviewed/revised preprints reviews.

If that's all true, we could represent it in the docmap as additional actions in the same step for VoR publish. They could have DOIs, license, URL, but without any other `content` URLs. We should be able to include the editors details too for eLife assessment/`evaluation-summary`. 

Does that shape and location look right @fred-atherden ? 

I'm not sure where you would find that data @HazalCiplak. I'm guessing it's all in the article XML, but maybe some in crossref too? @fred-atherden @gnott  - any suggestions?

**Comment by fred-atherden** [comment]
Thanks for this @HazalCiplak 

> Please note that in the "published" field, I have used the timestamp ("2023-05-15T17:19:12+00:00") from eJP for the decision "Pass to Production." On [the website](https://elifesciences.org/articles/86628), it appears as June 2, 2023. Therefore, it might be appropriate to use that date.

Yes, it would be appropriate to use June 2 2023 in this case, instead of the "Pass to Production." decision date (the latter indicates when an article has been QC OK'd for export from eJP into the Production process). 

> To answer your question more directly @HazalCiplak, I'd guess the peer review content isn't posted anywhere else publicly besides as part of our VoR article (no hypothesis, no sciety as it's not peer review on a preprint) and it is published at the same time as the VoR. Further - I'm guessing the peer review material will be similar, or the same as the previous reviewed/revised preprints reviews.

> If that's all true, we could represent it in the docmap as additional actions in the same step for VoR publish. They could have DOIs, license, URL, but without any other content URLs. We should be able to include the editors details too for eLife assessment/evaluation-summary.

> Does that shape and location look right @fred-atherden ?

@scottaubrey, thanks, yes that's all correct/appropriate to me.

I would be interested in @gnott's thoughts on where to retrieve this data. 

One option would be to retrieve this data from eLife's API, e.g. https://api.elifesciences.org/articles/86628. 

All the peer reviews are there (`elifeAssessment`, an array of `publicReviews` and `authorResponse`), and the dates are also available as `published` and `versionDate` (the latter date would be different to the former if we published a formal/visible new version, which we'd presumably want to replicate in docmaps/the timeline on EPP as well).

Note that there's currently no representation for the VOR version DOI (https://doi.org/10.7554/eLife.86628.3) at that API. I'd expect this to change in the near future, when we start displaying this on journal.

The article XML or Crossref are other possibilities. The XML can be found in [this repo](https://github.com/elifesciences/elife-article-xml), and I can point you to where you can find whatever information you'll need represented in the docmap.

I think Crossref will require multiple API requests, but I can suggest approaches to try to find data there if you'd prefer. One downside is that they will not have reliable version data (the visible new version of a VOR for example), as there currently isn't space to capture this information appropriately in their schema.

**Comment by gnott** [comment]
I agree with the data sources you've listed @fred-atherden. eLife API will have at least a stub for each peer review material and is the most limited data.

Crossref will have more data, and to avoid additional requests to a third party service is smart.

The data we sent to Crossref comes from the XML file, and it is probably the best place to get the data. The Python libraries I maintain use the XML as input and produces Crossref output. In data hub you may already have XML parsing logic which is easy for you to extract `<sub-article>` data.

I have another option to consider; the Crossref deposit files we generate and send to them could be another source of data, if data hub is able to parse Crossref's schema. The `elife-bot` workflow could send a copy of each to a place for data hub to read. Copies of these files are already stored in an S3 bucket folder for logging purposes.

**Comment by HazalCiplak** [comment]
Thank you all for your valuable comments! I appreciate your input. 

I have created [an investigation ticket](https://github.com/elifesciences/data-hub-issues/issues/723) specifically for the `published` field in the `vor-published` step. I will thoroughly review and explore each approach mentioned in the comments here to determine the best method to get the data.

In addition, I will proceed with merging this PR and continue development for the inclusion of VORs in DocMaps.

**Pull request merged**
